### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by iArchitSharma**
Fixed Typo

### CODE REVIEW

**Comment by iArchitSharma** [comment]
Hi I fixed some typo's in this code, its been 19 hours pull request is not merged?

**Comment by teor2345** [comment]
> Hi I fixed some typo's in this code, its been 19 hours pull request is not merged?

Why the rush?
Are you doing this pull request to get a prize?

If someone is offering prizes for doing pull requests, they should teach you how to do a helpful pull request. It's not your fault. They need to give you more help finding an active project.

I don't think this pull request is useful to us. We're not supporting Tor Messenger any more. So the website is not being used or maintained:
https://support.torproject.org/tormessenger/

**Comment by boklm** [comment]
I don't see any typo fixed in this commit, just a few letters changed to upper case for unknown reason (it doesn't look like those words are proper nouns).

And as @teor2345 said this website is not used anymore, so I think we can close this pull request.

**Comment by iArchitSharma** [comment]
Sorry for that I am just new to Open Source and trying to understand new things

> I don't see any typo fixed in this commit, just a few letters changed to upper case for unknown reason (it doesn't look like those words are proper nouns).
> 
> And as @teor2345 said this website is not used anymore, so I think we can close this pull request.


> > Hi I fixed some typo's in this code, its been 19 hours pull request is not merged?
> 
> Why the rush?
> Are you doing this pull request to get a prize?
> 
> If someone is offering prizes for doing pull requests, they should teach you how to do a helpful pull request. It's not your fault. They need to give you more help finding an active project.
> 
> I don't think this pull request is useful to us. We're not supporting Tor Messenger any more. So the website is not being used or maintained:
> https://support.torproject.org/tormessenger/

**Pull request closed without merging**
